export const LOADING_USER = 'LOADING_USER';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_ERRORS = 'GET_ERRORS';
export const SET_LOCATION_PATH = 'SET_LOCATION_PATH';
export const SET_UNNAUTHOROZID = 'SET_UNNAUTHOROZID';
export const FIRE_SSOSILENT = 'FIRE_SSOSILENT';
export const CLOSE_UNNAUTHOROZID_MODAL = 'CLOSE_UNNAUTHOROZID_MODAL';

