export const LOADING_ARCHIVES_DIRECTORIES = 'LOADING_ARCHIVES_DIRECTORIES';
export const GET_ARCHIVES_DIRECTORIES = 'GET_ARCHIVES_DIRECTORIES';

export const LOADING_ARCHIVES_FILES = 'LOADING_ARCHIVES_FILES';
export const GET_ARCHIVES_FILES = 'GET_ARCHIVES_FILES';
export const GET_ERRORS = 'GET_ERRORS';

export const SET_SORT = 'SET_SORT';
export const SET_SORT_BY_FILE_NAME = 'SET_SORT_BY_FILE_NAME';
export const SET_SORT_FILE_CATALOG = 'SET_SORT_FILE_CATALOG';
export const SET_SEARCH = 'SET_SEARCH';
