export const LOADING_ARCHIVES_DIRECTORIES = 'LOADING_ARCHIVES_DIRECTORIES';
export const GET_ARCHIVES_DIRECTORIES = 'GET_ARCHIVES_DIRECTORIES';

export const LOADING_ARCHIVES_FILES = 'LOADING_ARCHIVES_FILES';
export const GET_ARCHIVES_FILES = 'GET_ARCHIVES_FILES';
export const GET_ERRORS = 'GET_ERRORS';
